<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../Ferth/Autoloader.php';

/**
 * Test class for Autoloader.
 * Generated by PHPUnit on 2011-03-21 at 20:16:30.
 */
class AutoloaderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Autoloader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \Ferth\Autoloader(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'AutoloaderTestFiles');
        spl_autoload_register(array($this->object, 'load'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        spl_autoload_unregister(array($this->object, 'load'));
    }

    /**
     * The Autoloader has to load all classes.
     */
    public function testLoad()
    {
        // test normal class
        $a = new A;
        $this->assertThat($a, $this->isInstanceOf('A'));

        // test namespaced class
        $b = new TestNamespace\B;
        $this->assertThat($b, $this->isInstanceOf('\TestNamespace\B'));
    }

}

?>
