<?php

namespace Ferth;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../Ferth/PriorityList.php';

/**
 * Test class for PriorityList.
 * Generated by PHPUnit on 2011-04-05 at 19:24:46.
 */
class PriorityListTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var PriorityList
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new PriorityList;
    }

    protected function tearDown()
    {
        unset($this->object);
    }

    public function testEverything()
    {
       $this->object->insert('A', 0);
       $this->object->insert('B', 10);
       $this->object->insert('C', 10);

       $array = array();

       foreach($this->object as $value) {
           $array[] = $value;
       }

       $expected = array('B', 'C', 'A');

       $this->assertSame($expected, $array);
    }

}

?>
